# whether or not to send metrics to MCStats.org
collect-metrics: true
# List of Placeholders:
# ${no} amount of players
# ${no-1} amount of players minus 1
# ${n} player name
# ${reason} kick / ban reason
# ${admin} source of kick / ban
# --------------------------------------------
# JOIN / LEAVE MANAGER
# accepted placeholders : ${no}, ${no-1}, ${n} 
# --------------------------------------------

join-message: "&8(&7${no}&8) &f${n}&7 joined"
leave-message: "&8(&7${no-1}ยง8) &f${n}&7 left"
#only used if player randomly loses connection, for /kick see "KICK / BAN MANAGER"
kick-message: "&8(&7${no}&8) &f${n}&4 was kicked out"

# --------------------------------------------
# KICK / BAN MANAGER
# accepted placeholders : ${n}, ${reason}, ${admin}, ${reason}
# --------------------------------------------

admin-kick-message: "&8Player &c${n}&8 has been kicked by &c${admin}&8 for: &9${reason}"
admin-ban-message: "&8Player &c${n}&8 has been banned by &c${admin}&8 for: &9${reason}"
admin-unban-message: "&8Player &c${n}&8 has been unbanned by &c${admin}"
admin-banreason-message: "&8Player &c${n}&8 was banned for the reason: &9${reason}"
default-reason: asshat

# --------------------------------------------
# AFK MANAGER
# accepted placeholders : ${n}, ${message}
# --------------------------------------------

#specify the format you want afk messages to appear in
afk-format: "&3${n} &8${message}"

# set the default afk message
default-afk-message: "is now afk"

default-return-message: "has returned"
#whether you want to use a random afk messages (from the list added by /addafkmessages) or not
random-afk-messages: true

#whether AFK status should be removed upon interacting / moving / etc
toggle-afk-on-interact: true